const PLAN_FEATURES = {
    starter: {
        maxStudents: 200,
        maxTeachers: 5,
        maxSmsPerMonth: 0,
        homeworkEnabled: true,
        attendanceEnabled: true,
        feeManagementEnabled: true,
        parentPortalEnabled: true,
        reportsEnabled: false,
        customBrandingEnabled: false,
        admissionsEnabled: true,
        eventsEnabled: true,
        staffLeaveEnabled: false,
        staffAttendanceEnabled: false,
    },
    growth: {
        maxStudents: 600,
        maxTeachers: 20,
        maxSmsPerMonth: 500,
        homeworkEnabled: true,
        attendanceEnabled: true,
        feeManagementEnabled: true,
        parentPortalEnabled: true,
        reportsEnabled: true,
        customBrandingEnabled: false,
        admissionsEnabled: true,
        eventsEnabled: true,
        staffLeaveEnabled: true,
        staffAttendanceEnabled: true,
    },
    enterprise: {
        maxStudents: Infinity,
        maxTeachers: Infinity,
        maxSmsPerMonth: Infinity,
        homeworkEnabled: true,
        attendanceEnabled: true,
        feeManagementEnabled: true,
        parentPortalEnabled: true,
        reportsEnabled: true,
        customBrandingEnabled: true,
        admissionsEnabled: true,
        eventsEnabled: true,
        staffLeaveEnabled: true,
        staffAttendanceEnabled: true,
    },
};

module.exports = PLAN_FEATURES;
